### ISSUE TITLE
Màn hình chính

### ISSUE THREAD

**Issue by inFngNam** [nhatminhk63j/DrangonLearn.io#10]
### Màn hình chính gồm

- [ ] Tên tài khoản, ảnh avatar

- [ ] Khung chọn bài học ( chỉ chọn đc Fractions)

- [ ] Khung chọn game

- Đường dẫn ( Programme > Fractions > Common fractions) + Tên bài học (Parts and fractions)

- [ ] Game: ảnh game + tên game

**Comment by nhatminhk63j** [comment]
Đã hoàn thiện cơ bản giao diện, chưa hoàn chỉnh router link
