### ISSUE TITLE
Form đăng ký, đăng nhập 

### ISSUE THREAD

**Issue by inFngNam** [nhatminhk63j/drangonlearn.io#9]
- [x] Form đăng ký gồm : 

 - Email
 - Tên đăng nhập
 - Mật khẩu
 - Nhập lại mật khẩu

**Comment by inFngNam** [comment]
- [ ] Form đăng nhập gồm: 
 - Tên đăng nhập
 - Mật khẩu

**Comment by nhatminhk63j** [comment]
Done form đăng nhập
